version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
      JWT_SECRET_KEY: ${SECRET_KEY}
      HASH_ALGORITHM: ${HASH}
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: >
      bash -c "
        alembic upgrade head &&
        uvicorn main:app --reload --host 0.0.0.0 --port 8001
      "

volumes:
  postgres_data:

